import { randomUUID } from "node:crypto";
import type { QualityAssessment, QualityDimension, QualityInput, QualityPolicy, QualityReason } from "./types.js";
export const DEFAULT_QUALITY_POLICY: QualityPolicy = { version: "1", weights: { REQUIREMENT_COMPLIANCE: 20, EVIDENCE_GROUNDING: 20, EVIDENCE_COMPLETENESS: 15, FINDING_QUALITY: 15, COVERAGE: 10, INSTRUCTION_COMPLIANCE: 10, CONSISTENCY: 5, OUTPUT_VALIDITY: 5 }, acceptThreshold: 90, improveThreshold: 60, minimumCoverage: 0.9 };
const dimension = (score: number, explanation: string) => ({ score, applicable: true, explanation });
export function assessQuality(input: QualityInput, policy: QualityPolicy = DEFAULT_QUALITY_POLICY): QualityAssessment {
  const result = input.result; const required = input.requiredCoverage ?? 0; const covered = input.coveredResources ?? required; const coverage = required ? Math.max(0, Math.min(100, Math.round((covered / required) * 100))) : 100;
  const findingEvidence = result.findings.flatMap((finding) => finding.evidenceIds); const evidenceValid = input.evidenceValid ?? true; const grounding = result.findings.length === 0 ? 100 : evidenceValid && findingEvidence.length >= result.findings.length ? 100 : 0;
  const outputValid = result.status !== "FAILED" ? 100 : 0; const instructionValid = input.instructionValid ?? true; const securityOk = !input.securityViolation && !input.unauthorizedTool;
  const scores: Partial<Record<QualityDimension, { score: number; applicable: boolean; explanation: string }>> = {
    REQUIREMENT_COMPLIANCE: dimension(coverage, required ? `${covered} of ${required} required scope units covered.` : "No explicit coverage scope was supplied."), OUTPUT_VALIDITY: dimension(outputValid, outputValid ? "Structured result is valid." : "Agent result failed output validation."), EVIDENCE_GROUNDING: dimension(grounding, grounding ? "Factual findings reference validated evidence." : "One or more factual findings lack valid evidence."), EVIDENCE_COMPLETENESS: dimension(input.evidenceFresh === false ? 50 : grounding, input.evidenceFresh === false ? "Referenced evidence is stale." : "Evidence completeness follows grounded findings."), FINDING_QUALITY: dimension(result.findings.every((finding) => finding.title && finding.description) ? 100 : 0, "Finding structure was inspected deterministically."), COVERAGE: dimension(coverage, `${covered} of ${required || covered} scoped units covered.`), INSTRUCTION_COMPLIANCE: dimension(instructionValid ? 100 : 0, instructionValid ? "Required output and instruction constraints are satisfied." : "Instruction contract was not satisfied."), CONSISTENCY: dimension(100, "No deterministic contradiction was supplied."), SECURITY_COMPLIANCE: dimension(securityOk ? 100 : 0, securityOk ? "No security or permission violation was supplied." : "Security or permission violation detected."),
  };
  const blockingIssues: string[] = []; const reasonCodes: QualityReason[] = []; const improvementTargets: QualityAssessment["improvementTargets"] = [];
  const add = (code: QualityReason, key: QualityDimension, target: string, block = false) => { reasonCodes.push(code); improvementTargets.push({ dimension: key, reasonCode: code, target }); if (block) blockingIssues.push(target); };
  if (!securityOk) add(input.unauthorizedTool ? "UNAUTHORIZED_TOOL" : "SECURITY_VIOLATION", "SECURITY_COMPLIANCE", "Resolve the security or tool-permission violation before continuing.", true);
  if (!outputValid) add("OUTPUT_INVALID", "OUTPUT_VALIDITY", "Return a valid structured agent result.", true);
  if (!evidenceValid || grounding === 0) add("EVIDENCE_MISSING", "EVIDENCE_GROUNDING", "Provide valid evidence for every factual finding.", true);
  if (input.evidenceFresh === false) add("STALE_EVIDENCE", "EVIDENCE_COMPLETENESS", "Collect fresh evidence for time-sensitive findings.");
  if (coverage < policy.minimumCoverage * 100) add("LOW_COVERAGE", "COVERAGE", `Analyze the remaining ${Math.max(0, required - covered)} scoped resources.`);
  if (!instructionValid) add("INSTRUCTION_VIOLATION", "INSTRUCTION_COMPLIANCE", "Satisfy the mandatory instruction and output contract.", true);
  const score = Math.round(Object.entries(policy.weights).reduce((sum, [key, weight]) => sum + (scores[key as QualityDimension]?.score ?? 0) * (weight ?? 0), 0) / 100);
  const status = blockingIssues.length ? "BLOCK" : score >= policy.acceptThreshold ? "ACCEPT" : score >= policy.improveThreshold ? "NEEDS_IMPROVEMENT" : "REJECT";
  if (status !== "ACCEPT" && !reasonCodes.includes("LOW_QUALITY_SCORE")) reasonCodes.push("LOW_QUALITY_SCORE");
  return { qualityAssessmentId: randomUUID(), taskId: result.taskId, executionId: result.executionId, agentId: result.agentType, agentVersion: result.agentVersion, routingId: result.routingId, instructionPlanId: result.instructionPlanId, status, overallScore: score, dimensionScores: scores, blockingIssues, warnings: [], reasonCodes, improvementTargets, evidenceSummary: { referenced: result.evidenceReferences.length, grounded: findingEvidence.length }, requirementSummary: { required, covered }, qualityConfidence: securityOk && evidenceValid ? 100 : 50, policyVersion: policy.version, createdAt: new Date().toISOString() };
}
