import type { AgentResult, AgentType } from "../agents/types.js";
export const QUALITY_DIMENSIONS = ["REQUIREMENT_COMPLIANCE", "OUTPUT_VALIDITY", "EVIDENCE_GROUNDING", "EVIDENCE_COMPLETENESS", "FINDING_QUALITY", "COVERAGE", "INSTRUCTION_COMPLIANCE", "CONSISTENCY", "SECURITY_COMPLIANCE"] as const;
export type QualityDimension = (typeof QUALITY_DIMENSIONS)[number];
export type QualityDecision = "ACCEPT" | "NEEDS_IMPROVEMENT" | "REJECT" | "BLOCK";
export type QualityReason = "REQUIREMENT_MISSING" | "REQUIREMENT_PARTIAL" | "OUTPUT_INVALID" | "EVIDENCE_MISSING" | "EVIDENCE_INCOMPLETE" | "EVIDENCE_CONFLICT" | "LOW_COVERAGE" | "INSTRUCTION_VIOLATION" | "INTERNAL_CONTRADICTION" | "SECURITY_VIOLATION" | "UNAUTHORIZED_TOOL" | "LOW_QUALITY_SCORE" | "STALE_EVIDENCE" | "RESOURCE_SCOPE_MISMATCH";
export interface QualityPolicy { version: string; maxEvidenceAgeMs: number; minimumGroundingCoverage: number; minimumCleanScanConfidence: number; weights: Partial<Record<QualityDimension, number>>; acceptThreshold: number; improveThreshold: number; minimumCoverage: number; }
export interface QualityAssessment { qualityAssessmentId: string; taskId: string; executionId?: string; agentId: AgentType; agentVersion: string; routingId?: string; instructionPlanId?: string; status: QualityDecision; overallScore: number; dimensionScores: Partial<Record<QualityDimension, { score: number; applicable: boolean; explanation: string }>>; blockingIssues: string[]; warnings: string[]; reasonCodes: QualityReason[]; improvementTargets: Array<{ dimension: QualityDimension; reasonCode: QualityReason; target: string; affectedResource?: string }>; evidenceSummary: { referenced: number; grounded: number; coverage?: number; totalFindings?: number; unsupportedFindingIds?: string[]; invalidEvidenceIds?: string[]; staleEvidenceIds?: string[]; verified?: boolean }; requirementSummary: { required: number; covered: number }; qualityConfidence: number; policyVersion: string; createdAt: string; }
import type { EvidenceCheck } from "./evidence-check.js";
export interface PolicyGateOutcome { passed: boolean; violations?: string[]; }
export interface QualityInput { result: AgentResult; evidenceCheck?: EvidenceCheck; policyGate?: PolicyGateOutcome; requiredCoverage?: number; coveredResources?: number; evidenceValid?: boolean; evidenceFresh?: boolean; securityViolation?: boolean; unauthorizedTool?: boolean; instructionValid?: boolean; }
