import { useState } from "react";
import { Database, Fingerprint, GitBranch, Search, ShieldCheck } from "lucide-react";
import { Card, PageHeader } from "../../components/ui/Card";
import { ErrorState, IntegrationRequiredState, LoadingState } from "../../components/ui/DataState";
import { apiGetTaskEvidence, IntegrationRequired } from "../../services/api";

type EvidenceRow = { id: string; evidence_type: string; source_type: string; resource_reference: string | null; observed_at: string; freshness_status: string; status: string; content_hash: string };
export function Evidence() {
  const [taskId, setTaskId] = useState(""); const [items, setItems] = useState<EvidenceRow[] | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<Error | null>(null);
  const search = async () => { if (!taskId.trim()) return; setLoading(true); setError(null); try { const response = await apiGetTaskEvidence(taskId.trim()); if (response.error) throw new Error(response.error.message); setItems(response.data ?? []); } catch (err) { setError(err as Error); } finally { setLoading(false); } };
  if (error instanceof IntegrationRequired) return <IntegrationRequiredState feature="Evidence Intelligence" description="Evidence provenance is only shown from the connected backend; demo mode does not manufacture observations." />;
  return <div className="p-6 max-w-screen-xl mx-auto animate-slide-in"><PageHeader title="Evidence Intelligence" subtitle="Trace every grounded claim to an observed, scoped, and integrity-checked source." />
    <div className="grid grid-cols-1 xl:grid-cols-[1fr_280px] gap-6 items-start"><Card padding="none" className="overflow-hidden"><div className="p-5 border-b border-slate-100"><div className="flex flex-col sm:flex-row gap-3"><label className="sr-only" htmlFor="task-id">Task ID</label><input id="task-id" value={taskId} onChange={(event) => setTaskId(event.target.value)} onKeyDown={(event) => event.key === "Enter" && search()} placeholder="Enter task ID to inspect evidence" className="min-w-0 flex-1 rounded border border-slate-200 px-3 py-2 text-sm" /><button onClick={search} disabled={loading || !taskId.trim()} className="rounded bg-blue-700 text-white text-xs font-700 px-4 py-2 disabled:opacity-50"><span className="inline-flex items-center gap-2"><Search size={14} />Inspect task</span></button></div></div>{loading ? <LoadingState label="Loading tenant-scoped evidence…" /> : error ? <ErrorState title="Unable to load evidence" message={error.message} onRetry={search} /> : items ? items.length ? <div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="px-5 py-4 grid grid-cols-[1fr_auto] gap-3"><div className="min-w-0"><div className="flex gap-2 items-center"><span className="text-xs font-700 text-slate-800">{item.evidence_type}</span><span className="font-mono text-[10px] text-slate-400">{item.source_type}</span></div><p className="mt-1 text-xs text-slate-500 truncate">{item.resource_reference ?? "No resource reference"}</p><p className="mt-1 font-mono text-[10px] text-slate-400 truncate">{item.id} · {item.content_hash}</p></div><div className="text-right"><div className={`text-[10px] font-700 ${item.freshness_status === "FRESH" ? "text-emerald-700" : "text-amber-700"}`}>{item.freshness_status}</div><time className="block mt-1 text-[10px] text-slate-400">{new Date(item.observed_at).toLocaleString()}</time></div></div>)}</div> : <div className="p-12 text-center text-sm text-slate-500">No evidence has been collected for this task.</div> : <div className="p-12 text-center text-sm text-slate-500">Enter a task ID to inspect its evidence chain.</div>}</Card>
      <div className="space-y-3"><Card><ShieldCheck size={18} className="text-emerald-600 mb-3" /><h2 className="text-sm font-700 text-slate-900">Grounding boundary</h2><p className="mt-1.5 text-xs leading-relaxed text-slate-500">Findings are not authoritative until their required evidence exists, belongs to the active tenant and task, and is valid for the resource.</p></Card><Card><GitBranch size={18} className="text-violet-600 mb-3" /><h2 className="text-sm font-700 text-slate-900">Lineage</h2><p className="mt-1.5 text-xs leading-relaxed text-slate-500">Source → raw evidence → derived evidence → claim → finding. External content remains evidence, never an instruction.</p></Card><Card><Fingerprint size={18} className="text-blue-600 mb-3" /><h2 className="text-sm font-700 text-slate-900">Integrity</h2><p className="mt-1.5 text-xs leading-relaxed text-slate-500">Content hashes enable comparison without exposing sensitive payloads. Stored previews are redacted before persistence.</p></Card></div></div></div>;
}
