import { useState } from "react";
import { ShieldCheck, Target, Search } from "lucide-react";
import { Card, PageHeader } from "../../components/ui/Card";
import { ErrorState, IntegrationRequiredState, LoadingState } from "../../components/ui/DataState";
import { apiGetTaskQuality, IntegrationRequired } from "../../services/api";
type Assessment = { id: string; status: string; overall_score: number; dimension_scores: Record<string, { score: number; explanation: string }>; blocking_issues: string[]; reason_codes: string[]; improvement_targets: Array<{ target: string }>; created_at: string };
export function QualityControl() {
  const [taskId, setTaskId] = useState(""); const [items, setItems] = useState<Assessment[] | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<Error | null>(null);
  const load = async () => { if (!taskId.trim()) return; setLoading(true); setError(null); try { const response = await apiGetTaskQuality(taskId); if (response.error) throw new Error(response.error.message); setItems(response.data as Assessment[] ?? []); } catch (err) { setError(err as Error); } finally { setLoading(false); } };
  if (error instanceof IntegrationRequired) return <IntegrationRequiredState feature="Quality Verification" description="Quality assessments are shown only from the connected backend; demo mode does not invent scores or acceptance decisions." />;
  return <div className="p-6 max-w-screen-xl mx-auto animate-slide-in"><PageHeader title="Quality Verification" subtitle="Deterministic gates evaluate grounding, coverage, requirements, and policy compliance independently of model confidence." /><div className="grid grid-cols-1 xl:grid-cols-[1fr_280px] gap-6 items-start"><Card padding="none" className="overflow-hidden"><div className="p-5 border-b border-slate-100 flex gap-3"><input value={taskId} onChange={(e) => setTaskId(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} placeholder="Enter task ID" className="flex-1 rounded border border-slate-200 px-3 py-2 text-sm" /><button onClick={load} disabled={!taskId || loading} className="rounded bg-blue-700 px-4 text-xs font-700 text-white disabled:opacity-50"><Search size={14} /></button></div>{loading ? <LoadingState label="Loading assessments…" /> : error ? <ErrorState title="Unable to load quality history" message={error.message} onRetry={load} /> : items ? items.length ? <div className="divide-y divide-slate-100">{items.map((item) => <div key={item.id} className="p-5"><div className="flex justify-between gap-4"><div><div className="text-sm font-700 text-slate-900">{item.status}</div><div className="mt-1 text-xs font-mono text-slate-400">{item.id}</div></div><div className="text-3xl font-700 text-slate-900">{item.overall_score}<span className="text-sm text-slate-400">/100</span></div></div><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(item.dimension_scores ?? {}).map(([name, value]) => <div className="rounded border border-slate-100 px-3 py-2" key={name}><div className="text-[10px] font-mono text-slate-500">{name.replaceAll("_", " ")}</div><div className="mt-1 text-sm font-700 text-slate-800">{value.score}</div></div>)}</div>{item.blocking_issues?.length > 0 && <div className="mt-3 text-xs text-red-700">Blocking: {item.blocking_issues.join(" · ")}</div>}{item.improvement_targets?.length > 0 && <div className="mt-3 text-xs text-amber-700">Next: {item.improvement_targets.map((target) => target.target).join(" · ")}</div>}</div>)}</div> : <div className="p-12 text-center text-sm text-slate-500">No quality assessments exist for this task.</div> : <div className="p-12 text-center text-sm text-slate-500">Enter a task ID to inspect quality history.</div>}</Card><div className="space-y-3"><Card><ShieldCheck size={18} className="text-emerald-600 mb-3" /><h2 className="text-sm font-700 text-slate-900">Decision gate</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">Security, permission, output, and required-evidence failures block acceptance regardless of score.</p></Card><Card><Target size={18} className="text-violet-600 mb-3" /><h2 className="text-sm font-700 text-slate-900">Traceable improvement</h2><p className="mt-1 text-xs leading-relaxed text-slate-500">Non-acceptance produces explicit improvement targets, not hidden model reasoning.</p></Card></div></div></div>;
}
