import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { authenticate, requireOrgMember, requireRole } from "../middleware/auth.js";
import { EVIDENCE_SOURCES, EVIDENCE_TYPES } from "../ai/evidence/types.js";
import type { EvidenceInput, EvidenceSource, EvidenceType } from "../ai/evidence/types.js";
import { redactEvidence, stableEvidenceHash, validateEvidenceInput } from "../ai/evidence/validator.js";
import { query } from "../db/client.js";

const member = [authenticate, requireOrgMember]; const admin = [authenticate, requireOrgMember, requireRole("owner", "admin")];
const simulation = z.object({ taskId: z.string().min(1).max(200), evidenceType: z.enum([...EVIDENCE_TYPES] as [string, ...string[]]), sourceType: z.enum([...EVIDENCE_SOURCES] as [string, ...string[]]), sourceReference: z.string().min(1).max(2048), observedAt: z.string().datetime(), content: z.unknown().default(null), resourceReference: z.string().max(2048).optional() });
export async function evidenceRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.get("/ai/evidence/:id", { preHandler: member }, async (request, reply) => { const { rows } = await query(`SELECT id, evidence_type, source_type, resource_reference, observed_at, freshness_status, status, content_hash, metadata FROM evidence WHERE id=$1 AND org_id=$2`, [(request.params as { id: string }).id, request.orgId]); if (!rows[0]) return reply.status(404).send({ error: { code: "NOT_FOUND", message: "Evidence not found" } }); return reply.send({ data: rows[0] }); });
  fastify.get("/ai/tasks/:id/evidence", { preHandler: member }, async (request, reply) => { const { rows } = await query(`SELECT id, evidence_type, source_type, resource_reference, observed_at, freshness_status, status, content_hash FROM evidence WHERE task_id=$1 AND org_id=$2 ORDER BY collected_at DESC`, [(request.params as { id: string }).id, request.orgId]); return reply.send({ data: rows }); });
  fastify.get("/ai/findings/:id/evidence", { preHandler: member }, async (request, reply) => { const { rows } = await query(`SELECT e.id, e.evidence_type, e.source_type, e.resource_reference, e.observed_at, e.freshness_status, e.status, e.content_hash FROM evidence e JOIN findings f ON f.id=e.finding_id WHERE e.finding_id=$1 AND f.org_id=$2`, [(request.params as { id: string }).id, request.orgId]); return reply.send({ data: rows }); });
  fastify.get("/ai/evidence/:id/lineage", { preHandler: member }, async (request, reply) => { const id = (request.params as { id: string }).id; const { rows } = await query(`WITH RECURSIVE lineage AS (SELECT e.id, e.evidence_type, e.source_type, e.resource_reference, 0 depth FROM evidence e WHERE e.id=$1 AND e.org_id=$2 UNION ALL SELECT parent.id, parent.evidence_type, parent.source_type, parent.resource_reference, lineage.depth+1 FROM evidence_relationships r JOIN evidence parent ON parent.id=r.parent_evidence_id JOIN lineage ON lineage.id=r.child_evidence_id WHERE parent.org_id=$2) SELECT * FROM lineage ORDER BY depth`, [id, request.orgId]); return reply.send({ data: rows }); });
  fastify.post("/ai/evidence/simulate", { preHandler: admin }, async (request, reply) => { const parsed = simulation.safeParse(request.body); if (!parsed.success) return reply.status(400).send({ error: { code: "VALIDATION_ERROR", message: parsed.error.message } }); const input: EvidenceInput = { tenantId: request.orgId, taskId: parsed.data.taskId, evidenceType: parsed.data.evidenceType as EvidenceType, sourceType: parsed.data.sourceType as EvidenceSource, sourceReference: parsed.data.sourceReference, observedAt: parsed.data.observedAt, content: parsed.data.content ?? null, ...(parsed.data.resourceReference ? { resourceReference: parsed.data.resourceReference } : {}) }; const violations = validateEvidenceInput(input); return reply.send({ data: { valid: !violations.length, violations, contentHash: stableEvidenceHash(input.content), redactedPreview: redactEvidence(input.content), persisted: false, collected: false } }); });
}
