import { useState } from "react";
import { useNavigate } from "react-router";
import { ArrowRight, CheckCircle2, Globe2, ShieldCheck } from "lucide-react";
import { apiAddWebsite, apiVerifyOwnership, ApiCallError, IntegrationRequired } from "../../services/api";
import { ErrorState, IntegrationRequiredState } from "../../components/ui/DataState";
import { validateScanUrl } from "../../lib/validation";

export function AddWebsite() {
  const navigate = useNavigate(); const [url, setUrl] = useState(""); const [method, setMethod] = useState("html"); const [error, setError] = useState<Error | null>(null); const [saving, setSaving] = useState(false); const [website, setWebsite] = useState<{ id: string; domain: string; verification_token: string | null } | null>(null); const [verified, setVerified] = useState(false); const [checking, setChecking] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const check = validateScanUrl(url); if (!check.valid) { setError(new Error(check.error ?? "Enter a valid public URL.")); return; } setSaving(true); setError(null); try { const result = await apiAddWebsite(check.normalizedUrl ?? url, method); if (result.error) throw new ApiCallError(0, result.error.code, result.error.message); setWebsite(result.data as { id: string; domain: string; verification_token: string | null }); } catch (cause) { setError(cause as Error); } finally { setSaving(false); } };
  const verify = async () => { if (!website) return; setChecking(true); setError(null); try { const result = await apiVerifyOwnership(website.id); if (result.error) throw new ApiCallError(0, result.error.code, result.error.message); setVerified(true); } catch (cause) { setError(cause as Error); } finally { setChecking(false); } };
  if (error instanceof IntegrationRequired) return <IntegrationRequiredState feature="Add website" />;
  if (website) return <div className="mx-auto max-w-xl p-5 md:p-10"><p className="font-mono text-[11px] uppercase tracking-[.18em] text-blue-700">Ownership check</p><h2 className="mt-2 text-3xl font-800 tracking-tight text-slate-950">Verify {website.domain}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Add this token using the selected {method === "html" ? "HTML meta tag" : method === "dns" ? "DNS TXT record" : "verification file"}, then check the site.</p><div className="mt-8 rounded-md border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-700 uppercase tracking-[.12em] text-slate-500">Verification token</p><code className="mt-2 block break-all text-sm text-slate-900">{website.verification_token ?? "Token unavailable"}</code><p className="mt-3 text-xs leading-5 text-slate-500">The server fetches the public site and confirms this exact token before allowing scans.</p></div>{error && <div className="mt-5"><ErrorState title="Ownership check failed" message={error.message} /></div>}{verified ? <div className="mt-6 flex items-center gap-2 rounded-md bg-emerald-50 p-3 text-sm font-700 text-emerald-800"><CheckCircle2 size={17} />Ownership verified</div> : <button onClick={verify} disabled={checking} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-md bg-slate-950 px-4 py-3 text-sm font-700 text-white disabled:opacity-60">{checking ? "Checking website…" : "Check ownership"}<ShieldCheck size={15} /></button>}{verified && <button onClick={() => navigate("/websites")} className="mt-3 w-full rounded-md border border-slate-300 px-4 py-3 text-sm font-700 text-slate-700">Continue to websites</button>}</div>;
  return <div className="mx-auto max-w-xl p-5 md:p-10"><p className="font-mono text-[11px] uppercase tracking-[.18em] text-blue-700">Website onboarding</p><h2 className="mt-2 text-3xl font-800 tracking-tight text-slate-950">Connect a website</h2><p className="mt-2 text-sm leading-6 text-slate-500">Only submit websites you own or have explicit authorization to assess. Server-side URL validation blocks private and internal networks.</p><form onSubmit={submit} className="mt-8 space-y-6 border-t border-slate-200 pt-7"><label className="block"><span className="text-sm font-700 text-slate-800">Public website URL</span><div className="relative mt-2"><Globe2 size={17} className="absolute left-3 top-3 text-slate-400" /><input required value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://your-domain.com" className="w-full rounded-md border border-slate-300 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-blue-600" /></div></label><label className="block"><span className="text-sm font-700 text-slate-800">Verification method</span><select value={method} onChange={(event) => setMethod(event.target.value)} className="mt-2 w-full rounded-md border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="html">HTML meta tag</option><option value="dns">DNS TXT record</option><option value="file">Verification file</option><option value="qa_bypass">QA/Test Verification (authorized users only)</option></select></label>{method === "qa_bypass" && <div className="flex items-start gap-2 rounded-md bg-amber-50 p-3 text-xs leading-5 text-amber-900"><ShieldCheck size={15} className="mt-0.5 shrink-0" />This verification method is available only to authorized QA/admin users for the approved ZigmaNeural test domain. The server enforces this restriction.</div>}{error && <ErrorState title="Website could not be connected" message={error.message} />}<div className="flex items-start gap-2 rounded-md bg-blue-50 p-3 text-xs leading-5 text-blue-900"><ShieldCheck size={15} className="mt-0.5 shrink-0" />Ownership verification is required before a scan can start.</div><button disabled={saving} className="inline-flex w-full items-center justify-center gap-2 rounded-md bg-slate-950 px-4 py-3 text-sm font-700 text-white disabled:opacity-60">{saving ? "Connecting…" : "Connect website"}<ArrowRight size={15} /></button></form></div>;
}
